const ignoreTermList = [
  'Salvage',
  'Rebuilt',
  'Reconstruido',
  'Reconstructed',
  'Not a clean Title',
  'Our Super Shopper team and stuff are delighted to see each day in our store',
  'This vehicle is for sale by Advanced auto wholesale',
  'Our Dealership',
  'MC Lister',
  'www\\.',
  'Financing Options Available',
  'MIRA NUESTRO INVENTARIO',
  'Cars LLC',
  'Vehicle Exchange Program',
  'Harley Davidson',
  'Yamaha',
  'kawasaki',
  'Harley-Davidson',
  'can-am',
  'financing',
  'financiamiento',
  'financiamento',
  'financiamos',
  'Salvage',
  'Salvaged',
  'Recovered',
  'Odometer rollback',
  'Rebuilt',
  'Parts only',
  'Parting out',
  'Part car',
  'Dealer cars',
  'Autosales',
  'Autohaus',
  'Auto Haus',
  'Auto sales',
  'Auto Sales',
  'Autosale',
  'We Finance',
  'Financing available',
  'Llc',
  'Buy here pay here',
  '\\.com',
  'Address',
  'No payments',
  'Hablamos',
  'Preguntas',
  '✅',
  'Doc fee',
  'Financing available',
  'Thanks for looking at one of our many select pre-owned vehicles',
  'pre-owned vehicles',
  'Carfax certified',
  'Check availability',
  'Government fees',
  'Taxes',
  'La aprobación es rápida',
  'Compra aquí',
  'Ofrecemos garantía',
  'Price Posted is the down-payment',
  'El precio publicado es el pago inicial',
  'Down payment',
  'We approve you',
  'Financing',
  'Government vehicles',
  'I\\’m a dealer',
  "I'm a dealer",
  'Follow us on instagram',
  'Preapproved',
  'Pre approved',
  'Preapproval',
  'Pre approval',
  'Bad credit',
  'Down payment',
  'Just came in',
  'Take this one home today',
  'Take home today',
  'K1 motors',
  'Good credit',
  'No credit',
  'finanzas',
  'Salvage',
  'Flood car',
  'Flood damage',
  'Doesn’t drive',
  "Doesn't drive",
  'Doesnt drive',
  'Stolen',
  'Insurance claim',
  'Dealer cars',
  'Thanks for looking at one of my many select pre-owned vehicles',
  'Thanks for looking at one of my many',
  'Superbike',
  'financiado',
  'family owned',
  'family operated',
  'vehicleID',
  'vehicle ID',
  'stock number',
  'stock#',
  'stock #',
  // Add other terms here...
];

const ignoreTermsPattern = ignoreTermList.join('|');
const ignoreRegex = new RegExp(ignoreTermsPattern, 'i');

/**
 * @description
 * Takes a string and evaluates it with a regex expression to check if it matches any of the ignore terms
 * @param {*} testStr
 * @returns
 */
export const hasIgnoreTerm = (testStr: string) => ignoreRegex.test(testStr);
